name: Deploy web app

on:
  push:
    branches:
      - main

jobs:
  deploy-web-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install

      - name: Build app
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          keep_files: false
          publish_branch: gh-pages
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
